# CONFIGIRA INTERFACE GRÁFICA
# E INTERFACE COM BANCO DE DADOS 
interface:
  html:
   #list   : list.html   # escreve o arquivo .html literalmente na tela de listagem - não importa o mesmo arquivo duas vezes - nem é permitido passa um array de arquivos (* diminui substancialmente a performace da tela de listagem) 
    insert : updateInsert.html # escreve o arquivo .html literalmente na tela de inserção - não importa o mesmo arquivo duas vezes - nem é permitido passa um array de arquivos    
    update : updateInsert.html # escreve o arquivo .html literalmente na tela de atualização - não importa o mesmo arquivo duas vezes - nem é permitido passa um array de arquivos

  css:
    list   : [] # importa arquivos .css no cabeçãlho na tela de listagem - não importa o mesmo arquivo duas vezes   
    insert : [ 'style.css' ] # importa arquivos .css no cabeçãlho na tela de inserção - não importa o mesmo arquivo duas vezes   
    update : [ 'style.css' ] # importa arquivos .css no cabeçãlho na tela de atualização - não importa o mesmo arquivo duas vezes
    
  javascript:
    head:
      list   : [] # importa arquivos .js no cabeçãlho na tela de listagem - não importa o mesmo arquivo duas vezes
      insert : [ 'javascript.js' ] # importa arquivos .js no cabeçãlho na tela de inserção - não importa o mesmo arquivo duas vezes
      update : [ 'javascript.js'  ] # importa arquivos .js no cabeçãlho na tela de atualização - não importa o mesmo arquivo duas vezes

    body:
      list   : [] # escreve o arquivo .js literalmente na tela de listagem - pode importar o mesmo arquivo varias vezes
      insert : [ 'javascript-loadData.js' ] # escreve o arquivo .js literalmente na tela de inserção - pode importar o mesmo arquivo varias vezes
      update : [ 'javascript-loadData.js' ] # escreve o arquivo .js literalmente na tela de atualização - pode importar o mesmo arquivo varias vezes
     
# CONFIGURA PADRÕES DO TYPE
default:

  # parametros padrões
  parameter : 
    nullable : false
    year : 
      start : 'now'    # aceita um número inteiro ou 'now-[09]', 'now+[09]' ou apenas 'now'
      stop  : 'now-18' # aceita um número inteiro ou 'now-[09]', 'now+[09]' ou apenas 'now'
