# CONFIGIRA INTERFACE GRÁFICA
# E INTERFACE COM BANCO DE DADOS 
interface:
  html:
   #list   : list.html  
    insert : updateInsert.html
    update : updateInsert.html

  css:
    list   : []
    insert : []
    update : []
    
  javascript:
    head:
      list   : []
      insert : []
      update : []

    body:
      list   : []
      insert : []
      update : []
     
default:
  parameter : 
      nullable : false
