# CONFIGIRA INTERFACE GRÁFICA
# E INTERFACE COM BANCO DE DADOS 
interface:
  html:
   #list   : list.html  
    insert : insert.html
    update : update.html

  css:
    list   : [ "style.css" ]
    insert : [ "style.css" ]
    update : [ "style.css" ]
    
  javascript:
    head:
      list   : []
      insert : [ "javascript.js" ]
      update : [ "javascript.js" ]

    body:
      list   : []
      insert : []
      update : []
     
default:
  parameter : 
      nullable : false
