interface:
  html:
    #list   : []
    insert : updateInsert.html 
    update : updateInsert.html 
    dummy  : updateInsert.html 
  css:
    list   : [] 
    insert : [ 'style.css' ] 
    update : [ 'style.css' ] 
    dummy  : [ 'style.css' ] 
  javascript:
    head:
      list   : [] 
      insert : [' javascript.js' ] 
      update : [' javascript.js' ]  
      update : [' javascript.js' ] 
    body:
      list   : [] 
      insert : [ 'javascript-loadData.js' ]
      update : [ 'javascript-loadData.js' ]
      dummy  : [ 'javascript-loadData.js' ]
default:
  parameter : 
    nullable : false
    year : 
      start : 'now'    
      stop  : 'now-18' 
